-- ---------------------------------------------------------------------------
-- KnowMind Universe — registration store
--
-- Applied by `npm run db:migrate`, which is idempotent: every statement is
-- IF NOT EXISTS, so running it against an existing database is a no-op and
-- running it twice is safe.
--
-- This table is the lead list. It is NOT the authority on money — that remains
-- Razorpay, and a row only reaches PAID because the existing server-side
-- verification or the signed webhook said so.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS registrations (
  -- km_<base36>, generated by newRegistrationId(). Also the Razorpay receipt.
  id                  TEXT PRIMARY KEY,

  name                TEXT NOT NULL,
  email               TEXT NOT NULL,
  -- Ten local digits, the shape localMobileDigits() normalises to.
  mobile              TEXT NOT NULL,
  -- The three questions the registration modal no longer asks. Still in the
  -- schema, still written when supplied, so restoring them is a UI change only.
  gender              TEXT,
  age                 TEXT,
  occupation          TEXT,

  status              TEXT NOT NULL DEFAULT 'PENDING'
                        CHECK (status IN ('PENDING', 'PAID', 'PAYMENT_FAILED')),

  -- Paise, as this particular order was created. Historical orders were 999
  -- rupees (99900) before the price became 699 (69900), and the dashboard must
  -- show what was actually charged rather than restating today's constant.
  amount_paise        INTEGER NOT NULL,
  currency            TEXT NOT NULL DEFAULT 'INR',

  razorpay_order_id   TEXT UNIQUE,
  razorpay_payment_id TEXT,

  -- Which key pair produced the row, from the RAZORPAY_KEY_ID prefix. Test
  -- registrations are real rows with real timestamps; without this they would
  -- be indistinguishable from paying customers.
  key_mode            TEXT NOT NULL CHECK (key_mode IN ('test', 'live')),

  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  paid_at             TIMESTAMPTZ,
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- PAID is a claim about money. It may not be recorded without the payment id
  -- that proves it, whatever the calling code believes.
  CONSTRAINT paid_has_payment_id
    CHECK (status <> 'PAID' OR razorpay_payment_id IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS registrations_created_at_idx ON registrations (created_at DESC);
CREATE INDEX IF NOT EXISTS registrations_status_idx     ON registrations (status);
CREATE INDEX IF NOT EXISTS registrations_mode_idx       ON registrations (key_mode);
CREATE INDEX IF NOT EXISTS registrations_order_idx      ON registrations (razorpay_order_id);

-- ---------------------------------------------------------------------------
-- WhatsApp payment-confirmation delivery.
--
-- A PAID row's WhatsApp send is claimed with a single atomic UPDATE (see
-- claimWhatsappSend in src/lib/db/registrations.ts): it flips whatsapp_status
-- from NOT_SENT/FAILED to PENDING only WHERE it is still NOT_SENT/FAILED, and
-- Postgres's row lock is what guarantees that a verify request and a webhook
-- confirming the same payment at the same instant cannot both win the claim.
-- That guarantee only exists while this table exists, which is why sending is
-- skipped (and logged) rather than attempted when DATABASE_URL is unset — the
-- same fail-open policy as the rest of this file, applied to a place where
-- "fail open" would otherwise mean "maybe send it twice".
--
-- Added by ALTER TABLE, not by editing the CREATE TABLE above: the table
-- already exists in deployed databases, and db-migrate.mjs runs every
-- statement in this file every time (idempotent, per its own header comment).
-- ---------------------------------------------------------------------------

-- The CHECK is inline in the ADD COLUMN clause rather than a separate ADD
-- CONSTRAINT statement: Postgres has no `ADD CONSTRAINT IF NOT EXISTS`, and
-- db-migrate.mjs splits this file on a bare `;` (its own header comment says
-- so), so a `DO $$ ... $$` block's internal semicolons would be split into
-- broken statements. Attaching the CHECK here keeps every statement in this
-- file a single line ending in one semicolon, and on a second run the whole
-- clause — column and CHECK together — is skipped by IF NOT EXISTS.
ALTER TABLE registrations ADD COLUMN IF NOT EXISTS whatsapp_status TEXT NOT NULL DEFAULT 'NOT_SENT' CHECK (whatsapp_status IN ('NOT_SENT', 'PENDING', 'SENT', 'FAILED'));
ALTER TABLE registrations ADD COLUMN IF NOT EXISTS whatsapp_attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE registrations ADD COLUMN IF NOT EXISTS whatsapp_last_attempt_at TIMESTAMPTZ;
ALTER TABLE registrations ADD COLUMN IF NOT EXISTS whatsapp_sent_at TIMESTAMPTZ;
ALTER TABLE registrations ADD COLUMN IF NOT EXISTS whatsapp_message_id TEXT;
-- Sanitised (never the full Evolution Go response, never a header) — see
-- sanitizeWhatsappError in src/lib/whatsapp/evolution.ts.
ALTER TABLE registrations ADD COLUMN IF NOT EXISTS whatsapp_error TEXT;

CREATE INDEX IF NOT EXISTS registrations_whatsapp_status_idx ON registrations (whatsapp_status);

-- ---------------------------------------------------------------------------
-- Admin login attempts.
--
-- In the database rather than in memory because a per-instance counter on a
-- serverless platform limits nothing: each cold start begins at zero, and an
-- attacker gets a fresh allowance per lambda. This table is shared by every
-- instance, which is what makes the limit real.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS admin_login_attempts (
  id           BIGSERIAL PRIMARY KEY,
  ip           TEXT NOT NULL,
  succeeded    BOOLEAN NOT NULL,
  attempted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS admin_login_attempts_idx
  ON admin_login_attempts (ip, attempted_at DESC);
