"use client";

import Image from "next/image";
import { motion } from "motion/react";

import { Reveal, RevealGroup, revealChild } from "@/components/ui/Reveal";
import { forYouIf, kalee, notForYou, notForYouHeading, outcomes } from "@/lib/content";
import { programDetails } from "@/lib/config";

/* -------------------------------------------------------------------------- */
/*  Who it's for                                                               */
/*                                                                            */
/*  One art-directed composition, not a two-column layout. Four layers stack   */
/*  inside a single poster block:                                             */
/*                                                                            */
/*    0  a purple field, weighted to the left, with no straight edge anywhere  */
/*    1  Kaleeswaran, ghosted — the same cut-out, huge, purple-tinted, blurred */
/*    5  Kaleeswaran, foreground — monochrome, bleeding off the bottom edge    */
/*   10  a scrim that dissolves the figure into the copy, so there is no seam  */
/*   20  the copy                                                             */
/*                                                                            */
/*  About the photograph. `kaleeswaran-cutout.webp` is the project's own       */
/*  cut-out (`kalee/kaleeswaran.webp`) cropped to its opaque bounding box by   */
/*  `npm run optimize:assets` — the export carried ~250px of transparent       */
/*  padding on every side, which made precise placement impossible. That crop  */
/*  is the only change: no pixel of him is altered, and his face is never      */
/*  touched. The monochrome look is a CSS filter over the top, which the brief */
/*  for this section explicitly permits; remove `grayscale` and the original   */
/*  colour photograph is underneath, unchanged.                               */
/*                                                                            */
/*  The percentages on the two figures are art direction, not arbitrary: they  */
/*  frame him head-to-hip and let him run past the bottom edge, as the         */
/*  reference does. They only apply from `lg` up — below that the composition  */
/*  is restacked rather than shrunk, and the figure becomes a compact          */
/*  in-flow element so it can never sit under the text.                       */
/* -------------------------------------------------------------------------- */

const FIGURE = "/kalee/kaleeswaran-cutout.webp";
const FIGURE_W = 672;
const FIGURE_H = 1736;

/**
 * The phone's figure — a different file, for a reason worth stating.
 *
 * The cut-out above is the only one that exists: its original is 840x1120 and
 * the figure inside it is 328x863. That is enough to stand him at the side of a
 * desktop composition, where he is one element among several and never fills
 * the frame. It is not enough to crop to his head and run it the full width of
 * a phone, which is what the mobile band does — that asks for roughly four
 * times the detail the photograph holds, and no amount of resampling supplies
 * it. It looked exactly as broken as it was.
 *
 * This portrait is a real 1200x1050 photograph of him, already in the project
 * and already generated by the same pipeline. At 412px it renders at a third of
 * its native size, so it is sharp with nothing to prove. The grayscale grade is
 * the same one layer 5 wears, so the two compositions read as one section.
 */
const FIGURE_MOBILE = "/kalee/kaleeswaran-portrait.webp";
const FIGURE_MOBILE_W = 1200;
const FIGURE_MOBILE_H = 1050;

/* -------------------------------------------------------------------------- */

/*
 * The four persona marks that stood here are gone with the four personas.
 *
 * The deck answers "is this for me?" with seven statements rather than four
 * job titles, and a statement has nothing for an icon to depict — one drawing
 * per sentence would be decoration standing in for meaning. The number and its
 * hairline carry the index instead, which is the idiom this list already used
 * beside those icons. `MethodIcons` is a separate set and is untouched.
 */

export function AudienceSection() {
  return (
    <section
      id="who-its-for"
      aria-labelledby="audience-heading"
      className="relative isolate overflow-hidden bg-night-2 text-cream"
    >
      {/* ---- Layer 0 · the purple field ---- */}
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0 -z-10"
        style={{
          background:
            "radial-gradient(68% 78% at 24% 62%, rgba(59,28,90,0.92) 0%, rgba(59,28,90,0.34) 46%, transparent 74%)," +
            "radial-gradient(52% 58% at 6% 16%, rgba(90,35,72,0.5) 0%, transparent 72%)," +
            "linear-gradient(180deg, #140718 0%, #1b0a22 52%, #140718 100%)",
        }}
      />

      {/* ================= The poster ================= */}
      {/* `overflow-hidden` belongs here, not only on the section: the figure is
          taller than this block on purpose, and without a clip at *this* edge
          his legs carry on down behind the outcomes list below. */}
      <div className="relative overflow-hidden lg:min-h-[46rem]">
        {/*
          ---- Below `lg` · the figure, in flow above the copy ----

          The absolutely-positioned composition underneath cannot survive a
          narrow viewport: he is placed against the left of a frame whose right
          half holds the text, and there is no right half at 390px. So rather
          than shrinking that arrangement until he sits under the headline, the
          phone gets its own: one band, him at the top of it, the copy beneath.

          Same grayscale treatment as the desktop figure; a different source,
          for the reason set out at `FIGURE_MOBILE`. The scrim carries the band
          into the section colour so it ends on a dissolve, not an edge, exactly
          as layer 10 does on desktop.
        */}
        <div className="relative h-[15rem] sm:h-[18rem] lg:hidden">
          <Image
            alt={`${kalee.name}, ${kalee.roles[0]}`}
            src={FIGURE_MOBILE}
            width={FIGURE_MOBILE_W}
            height={FIGURE_MOBILE_H}
            sizes="100vw"
            // His face sits left of centre and high in this frame.
            className="h-full w-full object-cover object-[42%_22%] grayscale contrast-[1.12] brightness-[0.96]"
          />
          <div
            aria-hidden
            className="pointer-events-none absolute inset-0"
            style={{
              background:
                "linear-gradient(to bottom, rgba(20,7,24,0.45) 0%, rgba(20,7,24,0) 26%, rgba(20,7,24,0.55) 74%, rgba(20,7,24,0.98) 100%)",
            }}
          />
        </div>

        {/* ---- Layer 1 · the ghost. Same photograph, tinted and softened. ---- */}
        <Image
          aria-hidden
          alt=""
          src={FIGURE}
          width={FIGURE_W}
          height={FIGURE_H}
          sizes="45vw"
          className="pointer-events-none absolute top-[-16%] left-[17%] z-[1] hidden h-[172%] w-auto opacity-[0.20] [filter:grayscale(1)_sepia(1)_hue-rotate(244deg)_saturate(2.6)_brightness(0.72)_blur(3px)] lg:block"
        />

        {/* ---- Layer 5 · the figure, running past the bottom edge ---- */}
        <Image
          alt={`${kalee.name}, ${kalee.roles[0]}`}
          src={FIGURE}
          width={FIGURE_W}
          height={FIGURE_H}
          sizes="45vw"
          className="pointer-events-none absolute top-[7%] left-[1%] z-[5] hidden h-[152%] w-auto grayscale contrast-[1.12] brightness-[0.96] lg:block xl:left-[4%]"
        />

        {/* ---- Layer 10 · the scrim. No seam between figure and copy. ---- */}
        <div
          aria-hidden
          className="pointer-events-none absolute inset-0 z-10 hidden lg:block"
          style={{
            background:
              "linear-gradient(to right, rgba(20,7,24,0) 22%, rgba(20,7,24,0.5) 37%, rgba(20,7,24,0.88) 48%, rgba(20,7,24,0.96) 58%)," +
              "linear-gradient(to bottom, rgba(20,7,24,0.55) 0%, transparent 18%, transparent 82%, rgba(20,7,24,0.6) 100%)",
          }}
        />

        {/* ---- Layer 20 · the copy ---- */}
        <div className="relative z-20 container-page pt-10 pb-14 lg:py-20">
          <div className="lg:grid lg:grid-cols-12">
            <div className="lg:col-span-7 lg:col-start-6">
              {/* Quote mark, gold rule, label — the reference's opening beat. */}
              <Reveal>
                <div className="flex items-start gap-4">
                  <span
                    aria-hidden
                    className="-mt-3 font-serif text-[3.25rem] leading-none text-honey select-none sm:text-[4rem]"
                  >
                    &ldquo;
                  </span>
                  <span className="flex items-center gap-3 pt-1.5">
                    <span aria-hidden className="h-px w-7 bg-honey/70" />
                    <span className="text-eyebrow font-semibold tracking-[0.18em] text-honey uppercase">
                      Who it&rsquo;s for
                    </span>
                  </span>
                </div>
              </Reveal>

              <Reveal delay={0.06}>
                <h2
                  id="audience-heading"
                  className="mt-3 text-h1 font-semibold text-cream"
                >
                  This journey
                  <br />
                  is for <span className="text-honey">you</span> if&hellip;
                </h2>
              </Reveal>

              {/* ---- The seven ways this is for you ----
                  A column at every width: compact cards below `lg`, the ruled
                  index from `lg` — the treatment the four persona rows already
                  used, tightened for one sentence instead of a title and a
                  description.

                  Held at `text-base` from `lg` on purpose. The figure beside
                  this list is sized as a percentage of this block, so every
                  extra line of wrap in here scales him up with it; one line per
                  statement keeps the composition the size it was drawn at. */}
              <RevealGroup
                as="ul"
                className="mt-8 flex flex-col gap-2.5 lg:mt-12 lg:gap-0"
                stagger={0.05}
              >
                {forYouIf.map((point, i) => (
                  <motion.li
                    key={point}
                    variants={revealChild}
                    className="flex items-start gap-4 rounded-card border border-cream/10 bg-cream/[0.03] p-3.5 sm:gap-5 lg:gap-6 lg:rounded-none lg:border-0 lg:border-t lg:border-cream/[0.09] lg:bg-transparent lg:p-0 lg:py-3.5 lg:last:border-b"
                  >
                    <span className="flex shrink-0 items-center gap-2.5 pt-px sm:gap-3.5">
                      <span className="text-sm font-medium tabular-nums text-honey">
                        {String(i + 1).padStart(2, "0")}
                      </span>
                      <span aria-hidden className="h-px w-4 bg-honey/50 sm:w-6" />
                    </span>

                    <p className="min-w-0 text-sm text-cream sm:text-base">{point}</p>
                  </motion.li>
                ))}
              </RevealGroup>
            </div>
          </div>
        </div>
      </div>

      {/* ================= What may shift, and what this is not ================= */}
      <div className="relative z-20 container-page pb-[var(--spacing-section)]">
        <div className="rule-gold opacity-40" />

        <div className="mt-10 grid gap-10 sm:mt-14 sm:gap-14 lg:grid-cols-12 lg:gap-16">
          <div className="lg:col-span-7">
            <Reveal>
              <h3 className="text-eyebrow font-semibold tracking-[0.18em] text-honey uppercase">
                After {programDetails.days} days you may begin to&hellip;
              </h3>
            </Reveal>

            {/* The seven outcomes stack, and the row is tight enough on a
                phone — icon, one or two lines, 12px of padding — that the
                whole list still reads as a list rather than seven cards. */}
            <RevealGroup
              as="ul"
              className="mt-6 flex flex-col gap-2 lg:mt-8 lg:gap-0"
            >
              {outcomes.map((outcome) => (
                <motion.li
                  key={outcome}
                  variants={revealChild}
                  className="flex items-start gap-3.5 rounded-card border border-cream/10 bg-cream/[0.03] p-3.5 lg:gap-4 lg:rounded-none lg:border-0 lg:border-b lg:bg-transparent lg:p-0 lg:py-5"
                >
                  <svg
                    aria-hidden
                    viewBox="0 0 24 24"
                    fill="none"
                    className="mt-1 h-5 w-5 shrink-0 text-honey"
                  >
                    <path
                      d="m4.5 12.5 5 5 10-11"
                      stroke="currentColor"
                      strokeWidth="1.6"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                  </svg>
                  <span className="text-base text-cream lg:text-lead">{outcome}</span>
                </motion.li>
              ))}
            </RevealGroup>

            <Reveal delay={0.1}>
              <p className="mt-6 text-sm text-cream-dim">
                Written as &ldquo;may begin to&rdquo; on purpose. Fourteen days changes what you
                notice — what you then do with it stays yours.
              </p>
            </Reveal>
          </div>

          {/* Honest disqualification builds more trust than another promise. */}
          <div className="lg:col-span-5">
            <Reveal>
              <div className="rounded-card border border-cream/10 bg-purple-900/40 p-6 sm:p-9">
                <h3 className="text-eyebrow font-semibold tracking-[0.18em] text-cream-dim uppercase">
                  {notForYouHeading}
                </h3>

                <ul className="mt-5 flex flex-col gap-3.5 sm:mt-7 sm:gap-4">
                  {notForYou.map((item) => (
                    <li
                      key={item}
                      className="flex items-start gap-3.5 text-body text-cream-muted"
                    >
                      <span aria-hidden className="mt-[0.62em] h-px w-3.5 shrink-0 bg-cream/30" />
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
            </Reveal>
          </div>
        </div>
      </div>
    </section>
  );
}
